In [49]:
import numpy as np 
import pandas as pd

df = pd.read_csv('wilson.csv')

In [50]:
df.head()

,Name,Age,Sex,Ceruloplasmin Level,Copper in Blood Serum,Free Copper in Blood Serum,Copper in Urine,ALT,AST,Total Bilirubin,...,Neurological Symptoms Score,Psychiatric Symptoms,Cognitive Function Score,Family History,ATB7B Gene Mutation,Region,Socioeconomic Status,Alcohol Use,BMI,Is_Wilson_Disease
0,Daniel Perry,14,Female,9.341193,229.035586,NaN,144.987111,73.711588,72.047328,1.312437,...,5.078054,1,NaN,1,1,West,Low,False,25.219815,1
1,Lauren Luna,21,Female,9.149010,200.239637,16.153480,104.192937,25.896181,67.512312,0.221304,...,6.188963,0,96.844013,1,1,South,Medium,False,33.516525,1
2,Andrew Lewis,31,Male,9.768630,267.343650,14.373756,153.177037,45.918204,76.687723,3.533976,...,4.432626,1,69.162053,1,1,West,High,True,26.233051,1
3,Trevor Villegas,19,Male,11.915923,221.104453,4.326112,159.542682,53.625145,103.375310,1.549835,...,3.529333,1,77.317382,1,1,West,High,False,38.991556,1
4,John Mills,30,Female,9.500291,230.140212,23.433224,124.989992,68.076335,82.279210,3.895870,...,4.764693,0,70.502837,1,1,East,Low,True,32.787552,1

In [51]:
df['Is_Wilson_Disease'].value_counts()

Is_Wilson_Disease
0    40000
1    20000
Name: count, dtype: int64

In [52]:
df.count()

Name                                60000
Age                                 60000
Sex                                 60000
Ceruloplasmin Level                 53975
Copper in Blood Serum               53869
Free Copper in Blood Serum          54067
Copper in Urine                     53967
ALT                                 53889
AST                                 54138
Total Bilirubin                     54120
Albumin                             54023
Alkaline Phosphatase (ALP)          53935
Prothrombin Time / INR              53983
Gamma-Glutamyl Transferase (GGT)    54065
Kayser-Fleischer Rings              60000
Neurological Symptoms Score         53881
Psychiatric Symptoms                60000
Cognitive Function Score            54052
Family History                      60000
ATB7B Gene Mutation                 60000
Region                              60000
Socioeconomic Status                60000
Alcohol Use                         60000
BMI                                 60000
Is_Wilson_Disease                   60000
dtype: int64

In [53]:
y = df['Is_Wilson_Disease']
x = df.drop('Is_Wilson_Disease', axis=1)

In [54]:
x.head()

,Name,Age,Sex,Ceruloplasmin Level,Copper in Blood Serum,Free Copper in Blood Serum,Copper in Urine,ALT,AST,Total Bilirubin,...,Kayser-Fleischer Rings,Neurological Symptoms Score,Psychiatric Symptoms,Cognitive Function Score,Family History,ATB7B Gene Mutation,Region,Socioeconomic Status,Alcohol Use,BMI
0,Daniel Perry,14,Female,9.341193,229.035586,NaN,144.987111,73.711588,72.047328,1.312437,...,1,5.078054,1,NaN,1,1,West,Low,False,25.219815
1,Lauren Luna,21,Female,9.149010,200.239637,16.153480,104.192937,25.896181,67.512312,0.221304,...,1,6.188963,0,96.844013,1,1,South,Medium,False,33.516525
2,Andrew Lewis,31,Male,9.768630,267.343650,14.373756,153.177037,45.918204,76.687723,3.533976,...,1,4.432626,1,69.162053,1,1,West,High,True,26.233051
3,Trevor Villegas,19,Male,11.915923,221.104453,4.326112,159.542682,53.625145,103.375310,1.549835,...,1,3.529333,1,77.317382,1,1,West,High,False,38.991556
4,John Mills,30,Female,9.500291,230.140212,23.433224,124.989992,68.076335,82.279210,3.895870,...,0,4.764693,0,70.502837,1,1,East,Low,True,32.787552

In [55]:
df.isnull().sum()

Name                                   0
Age                                    0
Sex                                    0
Ceruloplasmin Level                 6025
Copper in Blood Serum               6131
Free Copper in Blood Serum          5933
Copper in Urine                     6033
ALT                                 6111
AST                                 5862
Total Bilirubin                     5880
Albumin                             5977
Alkaline Phosphatase (ALP)          6065
Prothrombin Time / INR              6017
Gamma-Glutamyl Transferase (GGT)    5935
Kayser-Fleischer Rings                 0
Neurological Symptoms Score         6119
Psychiatric Symptoms                   0
Cognitive Function Score            5948
Family History                         0
ATB7B Gene Mutation                    0
Region                                 0
Socioeconomic Status                   0
Alcohol Use                            0
BMI                                    0
Is_Wilson_Disease                      0
dtype: int64

In [56]:
# Replace only NaN values with the column mean
for column in df.columns:
    if df[column].isna().any():  # Check for NaN values
        mean_value = df[column].mean()  # Calculate mean (ignores NaN by default)
        df[column] = df[column].apply(lambda x: mean_value if pd.isna(x) else x)  # Replace NaN with mean

# Display the updated DataFrame
print(df)

                    Name  Age     Sex  Ceruloplasmin Level  \
0           Daniel Perry   14  Female             9.341193
1            Lauren Luna   21  Female             9.149010
2           Andrew Lewis   31    Male             9.768630
3        Trevor Villegas   19    Male            11.915923
4             John Mills   30  Female             9.500291
...                  ...  ...     ...                  ...
59995      Barbara Floyd   51    Male            16.691058
59996  Allison Maldonado   52  Female            18.337068
59997           Jody Lee   68  Female            20.148671
59998        David Roach   64  Female            21.075993
59999         Dave Hayes   69  Female            16.691058

       Copper in Blood Serum  Free Copper in Blood Serum  Copper in Urine  \
0                 229.035586                   15.002658       144.987111
1                 200.239637                   16.153480       104.192937
2                 267.343650                   14.373756       153.177037
3                 221.104453                    4.326112       159.542682
4                 230.140212                   23.433224       124.989992
...                      ...                         ...              ...
59995             101.555961                    4.632514        81.417747
59996             150.121897                   14.273579        63.641186
59997              25.627020                   12.657929        35.409964
59998             150.121897                   18.453320       104.962780
59999             113.710366                   15.002658        96.816591

             ALT         AST  Total Bilirubin  ...  \
0      73.711588   72.047328         1.312437  ...
1      25.896181   67.512312         0.221304  ...
2      45.918204   76.687723         3.533976  ...
3      53.625145  103.375310         1.549835  ...
4      68.076335   82.279210         3.895870  ...
...          ...         ...              ...  ...
59995  46.650124   24.352378         1.184147  ...
59996  54.852814   74.325954         1.255299  ...
59997  56.274310   20.130080         2.003615  ...
59998  60.797029   36.880050         1.249848  ...
59999  27.021787   45.649863         1.237234  ...

       Neurological Symptoms Score  Psychiatric Symptoms  \
0                         5.078054                     1
1                         6.188963                     0
2                         4.432626                     1
3                         3.529333                     1
4                         4.764693                     0
...                            ...                   ...
59995                     3.922783                     1
59996                     2.222558                     1
59997                     2.312080                     1
59998                     1.862371                     1
59999                     1.343535                     1

       Cognitive Function Score  Family History  ATB7B Gene Mutation  Region  \
0                     83.306548               1                    1    West
1                     96.844013               1                    1   South
2                     69.162053               1                    1    West
3                     77.317382               1                    1    West
4                     70.502837               1                    1    East
...                         ...             ...                  ...     ...
59995                 83.720242               0                    0    West
59996                 83.508571               0                    0    West
59997                 83.306548               0                    0    West
59998                 87.611491               0                    0    West
59999                 80.445653               0                    0   North

       Socioeconomic Status  Alcohol Use        BMI  Is_Wilson_Disease
0                       Low        False  25.219815                  1
1                    Medium        False  33.516525                  1
2                      High         True  26.233051                  1
3                      High        False  38.991556                  1
4                       Low         True  32.787552                  1
...                     ...          ...        ...                ...
59995                  High        False  31.890263                  0
59996                  High         True  34.589754                  0
59997                Medium         True  28.159348                  0
59998                Medium        False  35.831074                  0
59999                   Low         True  28.813391                  0

[60000 rows x 25 columns]

In [58]:
# from sklearn.model_selection import train_test_split
# from sklearn.classification import DecisionTreeClassifier
# from sklearn.metrics import accuracy_score

In [59]:
df['Is_Wilson_Disease'].value_counts()

Is_Wilson_Disease
0    40000
1    20000
Name: count, dtype: int64

In [61]:
df.dtypes

Name                                 object
Age                                   int64
Sex                                  object
Ceruloplasmin Level                 float64
Copper in Blood Serum               float64
Free Copper in Blood Serum          float64
Copper in Urine                     float64
ALT                                 float64
AST                                 float64
Total Bilirubin                     float64
Albumin                             float64
Alkaline Phosphatase (ALP)          float64
Prothrombin Time / INR              float64
Gamma-Glutamyl Transferase (GGT)    float64
Kayser-Fleischer Rings                int64
Neurological Symptoms Score         float64
Psychiatric Symptoms                  int64
Cognitive Function Score            float64
Family History                        int64
ATB7B Gene Mutation                   int64
Region                               object
Socioeconomic Status                 object
Alcohol Use                            bool
BMI                                 float64
Is_Wilson_Disease                     int64
dtype: object

In [68]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Handle missing values by replacing NaN with the column mean
# imputer = SimpleImputer(strategy='mean')
# df= pd.DataFrame(imputer.fit_transform(df), columns=df.columns)

# Encoding categorical variables
label_encoder = LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['Region'] = label_encoder.fit_transform(df['Region'])
df['Socioeconomic Status'] = label_encoder.fit_transform(df['Socioeconomic Status'])
df['Family History'] = label_encoder.fit_transform(df['Family History'])

# Feature and target variables
X = df.drop('Is_Wilson_Disease', axis=1)  # Drop the target column
y = df['Is_Wilson_Disease']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

# Initialize the models
models = {
    'Logistic Regression': LogisticRegression(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'Decision Tree': DecisionTreeClassifier(),
    'KNN': KNeighborsClassifier()
}

# Train and evaluate each model
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Calculate accuracy and other metrics
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Model: {model_name}")
    print(f"Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("="*50)

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

# Initialize the models
models = {
    'Logistic Regression': LogisticRegression(),
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'Decision Tree': DecisionTreeClassifier(),
    'KNN': KNeighborsClassifier()
}

# Train and evaluate each model
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    
    # Calculate accuracy and other metrics
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Model: {model_name}")
    print(f"Accuracy: {accuracy:.4f}")
    print("Classification Report:")
    print(classification_report(y_test, y_pred))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("="*50)

ValueError: could not convert string to float: 'Holly Aguilar'